# Generated by Django 5.1.3 on 2024-11-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("HospitalID", models.IntegerField(primary_key=True, serialize=False)),
                ("HospitalName", models.TextField()),
                ("Address", models.TextField()),
                ("ContactNumber", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "hospital",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("PatientID", models.IntegerField(primary_key=True, serialize=False)),
                ("DOB", models.TextField()),
                ("Gender", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "patient",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "UserHealthID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("Email", models.CharField(max_length=50)),
                ("PhoneNumber", models.CharField(max_length=50)),
                ("Height", models.IntegerField()),
                ("Weight", models.IntegerField()),
                ("Role", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("DoctorID", models.IntegerField(primary_key=True, serialize=False)),
                ("Specialization", models.TextField()),
                (
                    "Doctor_HospitalID",
                    models.ForeignKey(
                        db_column="Doctor_HospitalID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.hospital",
                    ),
                ),
                (
                    "DUserHealthID",
                    models.ForeignKey(
                        db_column="DUserHealthID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.users",
                    ),
                ),
            ],
            options={
                "db_table": "doctor",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "AppointmentID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("AppointmentDate", models.TextField()),
                (
                    "Hospital_ID",
                    models.ForeignKey(
                        db_column="Hospital_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.hospital",
                    ),
                ),
                (
                    "Patient_ID",
                    models.ForeignKey(
                        db_column="Patient_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
            ],
            options={
                "db_table": "appointment",
            },
        ),
        migrations.CreateModel(
            name="PatientDiagnosis",
            fields=[
                ("DiagnosisID", models.IntegerField(primary_key=True, serialize=False)),
                ("DiagnosisDetails", models.TextField()),
                (
                    "Doctor_ID",
                    models.ForeignKey(
                        db_column="Doctor_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.doctor",
                    ),
                ),
                (
                    "Patient_ID",
                    models.ForeignKey(
                        db_column="Patient_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
            ],
            options={
                "db_table": "paitent_diagnosis",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("PaymentID", models.IntegerField(primary_key=True, serialize=False)),
                ("TranStatus", models.CharField(max_length=50)),
                (
                    "Hospital_ID",
                    models.ForeignKey(
                        db_column="Hospital_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.hospital",
                    ),
                ),
                (
                    "Patient_ID",
                    models.ForeignKey(
                        db_column="Patient_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("PresID", models.IntegerField(primary_key=True, serialize=False)),
                ("Medicines", models.TextField()),
                ("Comments", models.TextField()),
                (
                    "DoctorPres_ID",
                    models.ForeignKey(
                        db_column="DoctorPres_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.doctor",
                    ),
                ),
                (
                    "PatientPres_ID",
                    models.ForeignKey(
                        db_column="PatientPres_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
            ],
            options={
                "db_table": "prescription",
            },
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                ("ReportID", models.IntegerField(primary_key=True, serialize=False)),
                ("TestName", models.TextField()),
                ("SampleCollected", models.TextField()),
                ("Observation", models.TextField()),
                ("SampleType", models.TextField()),
                (
                    "Patient_ReportID",
                    models.ForeignKey(
                        db_column="Patient_ReportID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="PatientVisit",
            fields=[
                ("VisitReason", models.TextField()),
                ("VisitNotes", models.TextField()),
                ("VisitID", models.IntegerField(primary_key=True, serialize=False)),
                ("VisitDate", models.TextField()),
                (
                    "AppointmentID",
                    models.ForeignKey(
                        db_column="AppointmentID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.appointment",
                    ),
                ),
                (
                    "DiagnosisID",
                    models.ForeignKey(
                        db_column="DiagnosisID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patientdiagnosis",
                    ),
                ),
                (
                    "Doctor_ID",
                    models.ForeignKey(
                        db_column="Doctor_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.doctor",
                    ),
                ),
                (
                    "Patient_ID",
                    models.ForeignKey(
                        db_column="Patient_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
                (
                    "PresID",
                    models.ForeignKey(
                        db_column="PresID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.prescription",
                    ),
                ),
                (
                    "ReportID",
                    models.ForeignKey(
                        db_column="ReportID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.reports",
                    ),
                ),
            ],
            options={
                "db_table": "patient_visit",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="PUserHealthID",
            field=models.ForeignKey(
                db_column="PUserHealthID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.users",
            ),
        ),
        migrations.CreateModel(
            name="PatientDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Doctor_ID",
                    models.ForeignKey(
                        db_column="Doctor_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.doctor",
                    ),
                ),
                (
                    "Patient_ID",
                    models.ForeignKey(
                        db_column="Patient_ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_doctor",
                "unique_together": {("Patient_ID", "Doctor_ID")},
            },
        ),
    ]
