# Generated by Django 5.1.3 on 2024-11-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="patientdiagnosis",
            table="patient_diagnosis",
        ),
    ]
